const BUILD = 'RC1 Build 001';
const KEY = 'gt7cm_rc1_build001_state';
const defaults = {
  meta:{version:BUILD, created:new Date().toISOString()},
  garage:[], activeChampionshipId:null, championships:[], trash:[],
  library:{
    categories:['GT3','GT4','VGT','Formula GT7','Road Cars','Deportivos Modernos','Deportivos Clásicos','American Sportcars','American Classics','Personalizada'],
    subcategories:['World Series','Endurance','America 70s','Muscle Cars','Ferrari F40 Cup','JDM 90s','Personalizada'],
    points:{name:'GT ampliado', values:[25,20,16,13,11,10,9,8,7,6,5,4,3,2,1,0,0,0,0,0], pole:1, fastest:1}
  }
};
let state = load();
let view = 'home';
let modal = null;
function load(){try{return {...structuredClone(defaults), ...(JSON.parse(localStorage.getItem(KEY))||{})}}catch(e){return structuredClone(defaults)}}
function save(){state.meta.version=BUILD;localStorage.setItem(KEY,JSON.stringify(state));}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function car(id){return GT7_CARS.find(c=>c.id===id)}
function ownedCars(){return GT7_CARS.filter(c=>state.garage.includes(c.id))}
function activeChamp(){return state.championships.find(c=>c.id===state.activeChampionshipId) || state.championships[0]}
function setView(v){view=v;modal=null;render();}
function showModal(type,data={}){modal={type,data};render();}
function closeModal(){modal=null;render();}
function app(html){document.getElementById('app').innerHTML=`<main class="shell"><header class="top"><div class="row"><div class="logo">GT</div><div class="brand"><b>GT7 Championship Manager</b><span>${BUILD} · Designed by JDM & ChatGPT</span></div></div><button class="pill" onclick="showModal('about')">Acerca de</button></header>${html}</main>${tabs()}${modalHtml()}`}
function tabs(){const items=[['home','🏠','Inicio'],['championships','🏁','Campeonatos'],['garage','🚗','Garaje GT7'],['library','📚','Biblioteca'],['settings','⚙️','Ajustes']];return `<nav class="tabs"><div class="tabs-inner">${items.map(i=>`<button class="tab ${view===i[0]?'on':''}" onclick="setView('${i[0]}')"><b>${i[1]}</b>${i[2]}</button>`).join('')}</div></nav>`}
function render(){if(view==='home')return app(home()); if(view==='garage')return app(garage()); if(view==='championships')return app(championships()); if(view==='library')return app(library()); if(view==='settings')return app(settings());}
function home(){const ch=activeChamp(); if(!state.garage.length) return `<section class="hero"><h1>Empieza creando tu Garaje GT7</h1><p>Marca los coches que tienes en el juego. La plantilla GT7 de cada campeonato se construirá desde este garaje.</p></section><button class="btn" onclick="setView('garage')">Crear Garaje GT7</button>`; if(!ch) return `<section class="hero"><h1>Tu garaje ya está listo</h1><p>Ahora crea tu primer campeonato y la plantilla que replicarás en las carreras personalizadas de GT7.</p></section><button class="btn" onclick="showModal('champWizard')">Crear campeonato</button>`; const next=nextRace(ch); const standings=standingsFor(ch); return `<section class="hero"><span class="badge">Campeonato activo</span><h1>${ch.name}</h1><p>${ch.category} · ${ch.subcategory || 'Sin subcategoría'} · Carrera ${Math.min((ch.currentRace||0)+1,ch.calendar.length)}/${ch.calendar.length}</p></section><div class="grid two"><div class="card"><h2>🏁 Próxima carrera</h2>${next?`<h3>${next.circuit}</h3><p class="muted">${next.laps} vueltas · ${next.weather} · ${next.daytime}</p><button class="btn" onclick="showModal('raceControl',{champId:'${ch.id}'})">Continuar en Race Control</button>`:'<p class="muted">Campeonato completado.</p>'}</div><div class="card"><h2>📊 Clasificación</h2>${standings.length?standings.slice(0,5).map((s,i)=>`<div class="item"><div><b>${i+1}. ${s.name}</b><br><small>${s.carName}</small></div><b>${s.points}</b></div>`).join(''):'<p class="muted">Aún no hay resultados.</p>'}</div></div>`}
function garage(){const q=(document.getElementById('searchGarage')?.value||'').toLowerCase(); const groups={}; GT7_CARS.filter(c=>(c.make+' '+c.model+' '+c.year+' '+c.category+' '+c.sub).toLowerCase().includes(q)).forEach(c=>{(groups[c.make]??=[]).push(c)}); const owned=state.garage.length; return `<section class="hero"><h1>Garaje GT7</h1><p>${owned} coches marcados como disponibles. Sólo estos podrán usarse en plantillas GT7 con “Seleccionar desde el garaje”.</p></section><div class="card field"><label>Buscar coche</label><input id="searchGarage" placeholder="Mustang, Porsche, Gr.3…" oninput="render()"></div><div class="grid">${Object.keys(groups).sort().map(make=>`<div class="card"><div class="row"><h2>${make}</h2><span class="pill">${groups[make].filter(c=>state.garage.includes(c.id)).length}/${groups[make].length}</span></div><div class="list">${groups[make].map(c=>`<div class="item"><div><b>${c.model} '${String(c.year).slice(-2)}</b><br><small>${c.category} · ${c.sub} · ${c.country}</small></div><button class="btn ${state.garage.includes(c.id)?'secondary':''}" onclick="toggleGarage('${c.id}')">${state.garage.includes(c.id)?'En garaje':'Añadir'}</button></div>`).join('')}</div></div>`).join('')}</div>`}
function toggleGarage(id){state.garage=state.garage.includes(id)?state.garage.filter(x=>x!==id):[...state.garage,id];save();render();}
function championships(){return `<section class="hero"><h1>Campeonatos</h1><p>Gestiona campeonatos activos, archivados y plantillas GT7.</p></section><button class="btn" onclick="showModal('champWizard')">Nuevo campeonato</button><div class="grid" style="margin-top:12px">${state.championships.length?state.championships.map(ch=>champCard(ch)).join(''):'<div class="card empty">Aún no hay campeonatos.</div>'}</div>`}
function champCard(ch){const next=nextRace(ch); return `<div class="card"><div class="row"><div><h2>${ch.name}</h2><p class="muted">${ch.category} · ${ch.subcategory} · ${ch.status}</p></div><span class="badge">${(ch.results||[]).length}/${ch.calendar.length}</span></div><div class="divider"></div><p class="muted">Próxima: ${next?next.circuit:'Finalizado'}</p><div class="row"><button class="btn" onclick="state.activeChampionshipId='${ch.id}';save();showModal('raceControl',{champId:'${ch.id}'})">Continuar</button><button class="btn secondary" onclick="showModal('editChamp',{champId:'${ch.id}'})">Editar</button><button class="btn danger" onclick="deleteChamp('${ch.id}')">Eliminar</button></div></div>`}
function library(){const cats=state.library.categories; return `<section class="hero"><h1>Biblioteca</h1><p>Categorías, subcategorías, sistemas de puntos y circuitos reutilizables.</p></section><div class="grid two"><div class="card"><h2>Categorías base</h2><div class="list">${cats.map(c=>`<div class="item"><b>${c}</b><small>${GT7_CARS.filter(x=>x.category===c).length} coches</small></div>`).join('')}</div></div><div class="card"><h2>Circuitos de asfalto</h2><div class="list">${GT7_CIRCUITS.map(c=>`<div class="item"><b>${c.name}</b><small>${c.country}${c.special?' · '+c.special:''}</small></div>`).join('')}</div></div></div>`}
function settings(){return `<section class="hero"><h1>Ajustes</h1><p>Copias de seguridad, restauración y datos locales.</p></section><div class="grid"><div class="card"><h2>Datos locales</h2><p class="muted">Todo se guarda en este iPhone/navegador mediante almacenamiento local.</p><div class="row"><button class="btn" onclick="exportData()">Exportar backup</button><button class="btn secondary" onclick="document.getElementById('importFile').click()">Importar</button></div><input id="importFile" type="file" accept="application/json" class="hidden" onchange="importData(event)"></div><div class="card"><h2>Reset</h2><p class="muted">Borra todos los datos de prueba de esta Build.</p><button class="btn danger" onclick="resetAll()">Borrar datos</button></div></div>`}
function modalHtml(){if(!modal)return ''; const t=modal.type,d=modal.data||{}; let body=''; if(t==='about')body=`<h2>GT7 Championship Manager</h2><p class="muted">${BUILD}</p><p>Designed by JDM & ChatGPT</p><p class="muted">Companion app para campeonatos offline de Gran Turismo 7.</p><button class="btn" onclick="closeModal()">Cerrar</button>`; if(t==='champWizard')body=champWizard(); if(t==='raceControl')body=raceControl(d.champId); if(t==='editChamp')body=editChamp(d.champId); return `<div class="modal" onclick="if(event.target.className==='modal')closeModal()"><div class="sheet">${body}</div></div>`}
function champWizard(){if(ownedCars().length<1)return `<h2>Antes necesitas coches en Garaje GT7</h2><p class="muted">Marca al menos un coche como disponible.</p><button class="btn" onclick="closeModal();setView('garage')">Ir al garaje</button>`; return `<h2>Nuevo campeonato</h2><div class="form"><div class="field"><label>Nombre</label><input id="cw_name" value="Gr.3 World Series"></div><div class="field"><label>Temporada</label><input id="cw_season" value="2026"></div><div class="field"><label>Categoría</label><select id="cw_cat" onchange="suggestSub()">${state.library.categories.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>Subcategoría</label><input id="cw_sub" value="World Series"></div><div class="field"><label>Nombre del ajuste guardado en GT7</label><input id="cw_template" value="GT7 CM - Gr.3 World Series"></div><div class="field"><label>Número de carreras</label><select id="cw_races">${[5,8,10,12].map(n=>`<option ${n===10?'selected':''}>${n}</option>`).join('')}</select></div><button class="btn" onclick="createChamp()">Crear y continuar</button><button class="btn secondary" onclick="closeModal()">Cancelar</button></div>`}
function suggestSub(){const cat=document.getElementById('cw_cat').value; const sub=document.getElementById('cw_sub'); const map={'GT3':'World Series','GT4':'Cup','VGT':'Vision Trophy','Formula GT7':'Formula Championship','Road Cars':'Deportivos Modernos','American Classics':'America 70s'}; sub.value=map[cat]||'Personalizada'}
function createChamp(){const n=document.getElementById('cw_name').value.trim()||'Nuevo campeonato'; const cat=document.getElementById('cw_cat').value; const count=Number(document.getElementById('cw_races').value); const circuits=GT7_CIRCUITS.slice(0,count); const owned=ownedCars(); const grid=Array.from({length:20},(_,i)=>({id:uid('drv'),number:i+1,name:i===0?'JDM':`IA ${String(i).padStart(2,'0')}`,type:i===0?'Usuario':'IA',carId:owned[i%owned.length].id})); const ch={id:uid('ch'),name:n,season:document.getElementById('cw_season').value,category:cat,subcategory:document.getElementById('cw_sub').value,status:'Preparación',gt7Template:document.getElementById('cw_template').value,grid,calendar:circuits.map((c,i)=>({id:uid('race'),index:i+1,circuit:c.name,laps:c.name.includes('Nordschleife')?3:10,weather:'Variable',daytime:'Tarde',bop:'Activado',fuel:'x3',tyres:'x5',state:'Pendiente'})),results:[],currentRace:0}; state.championships.push(ch); state.activeChampionshipId=ch.id;save();closeModal();setView('home')}
function editChamp(id){const ch=state.championships.find(c=>c.id===id); if(!ch)return ''; return `<h2>Editar campeonato</h2><div class="form"><div class="field"><label>Nombre</label><input id="ec_name" value="${esc(ch.name)}"></div><div class="field"><label>Ajuste GT7</label><input id="ec_template" value="${esc(ch.gt7Template)}"></div><div class="field"><label>Parrilla / coches</label></div>${ch.grid.map((p,i)=>`<div class="item"><div style="width:72px"><input id="pnum_${i}" value="${p.number}"></div><div style="flex:1"><input id="pname_${i}" value="${esc(p.name)}"></div><select id="pcar_${i}">${ownedCars().map(c=>`<option value="${c.id}" ${c.id===p.carId?'selected':''}>${c.make} ${c.model} '${String(c.year).slice(-2)}</option>`).join('')}</select></div>`).join('')}<button class="btn" onclick="saveChampEdit('${id}')">Guardar cambios</button><button class="btn secondary" onclick="closeModal()">Cerrar</button></div>`}
function saveChampEdit(id){const ch=state.championships.find(c=>c.id===id); ch.name=document.getElementById('ec_name').value; ch.gt7Template=document.getElementById('ec_template').value; ch.grid.forEach((p,i)=>{p.number=document.getElementById('pnum_'+i).value;p.name=document.getElementById('pname_'+i).value;p.carId=document.getElementById('pcar_'+i).value});save();closeModal();render();}
function raceControl(id){const ch=state.championships.find(c=>c.id===id); const race=nextRace(ch); if(!race)return `<h2>Campeonato finalizado</h2><button class="btn" onclick="closeModal()">Cerrar</button>`; return `<h2>Race Control</h2><p class="muted">${ch.name} · Carrera ${race.index}/${ch.calendar.length}</p><div class="card"><h3>${race.circuit}</h3><p class="muted">Carga en GT7 el ajuste guardado: <b>${ch.gt7Template}</b></p><div class="list">${['Plantilla GT7','Circuito','Vueltas','BoP','Consumo','Desgaste','Clima'].map((x,i)=>`<label class="item"><span>✔ ${x}</span><input type="checkbox" checked></label>`).join('')}</div></div><div class="card"><h3>Registrar resultado</h3><div class="form"><div class="field"><label>Tu posición</label><select id="res_pos">${Array.from({length:20},(_,i)=>`<option>${i+1}</option>`).join('')}</select></div><div class="row"><label><input id="res_pole" type="checkbox"> Pole</label><label><input id="res_fast" type="checkbox"> Vuelta rápida</label></div><button class="btn" onclick="saveResult('${ch.id}','${race.id}')">Actualizar campeonato</button></div></div><button class="btn secondary" onclick="closeModal()">Cerrar</button>`}
function saveResult(chid,rid){const ch=state.championships.find(c=>c.id===chid); const race=ch.calendar.find(r=>r.id===rid); const pos=Number(document.getElementById('res_pos').value); const pole=document.getElementById('res_pole').checked; const fastest=document.getElementById('res_fast').checked; const values=state.library.points.values; const res={raceId:rid, userPosition:pos, pole, fastest, points:(values[pos-1]||0)+(pole?1:0)+(fastest?1:0), date:new Date().toISOString()}; ch.results=ch.results.filter(r=>r.raceId!==rid); ch.results.push(res); race.state='Disputada'; ch.currentRace=Math.min((ch.currentRace||0)+1,ch.calendar.length); ch.status=ch.currentRace>=ch.calendar.length?'Finalizado':'En curso'; save();closeModal();setView('home');}
function standingsFor(ch){if(!ch)return []; const user=ch.grid[0]; const base=ch.grid.map(p=>({id:p.id,name:p.name,carName:(car(p.carId)?.make||'')+' '+(car(p.carId)?.model||''),points:0,wins:0})); const u=base[0]; (ch.results||[]).forEach(r=>{u.points+=r.points;if(r.userPosition===1)u.wins++; base.slice(1).forEach((b,i)=>{const synthetic=Math.max(1, ((i+2 + r.userPosition*3 + (ch.results.indexOf(r)*2))%20)+1); b.points+=state.library.points.values[synthetic-1]||0; if(synthetic===1)b.wins++;});}); return base.sort((a,b)=>b.points-a.points||b.wins-a.wins)}
function nextRace(ch){return ch.calendar.find(r=>r.state!=='Disputada')}
function deleteChamp(id){if(!confirm('¿Mover este campeonato a la papelera?'))return; const ch=state.championships.find(c=>c.id===id); state.trash.push({...ch,deletedAt:new Date().toISOString()}); state.championships=state.championships.filter(c=>c.id!==id); if(state.activeChampionshipId===id)state.activeChampionshipId=state.championships[0]?.id||null;save();render();}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='gt7cm-backup-'+Date.now()+'.json'; a.click();}
function importData(e){const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{state=JSON.parse(r.result);save();render();}catch(err){alert('Archivo no válido')}}; r.readAsText(f)}
function resetAll(){if(confirm('¿Borrar todos los datos locales?')){state=structuredClone(defaults);save();render();}}
function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();
