(()=>{
const VERSION='RC1 Build 002';
const KEY='gt7cm_rc1_data_v1';
const $=s=>document.querySelector(s);
const uid=()=>Math.random().toString(36).slice(2,10);
const defaultPoints=[25,20,16,13,11,10,9,8,7,6,5,4,3,2,1];
const cats=['GT3','GT4','VGT','Formula GT7','Road Cars','Deportivos Modernos','Deportivos Clásicos','American Sportcars','American Classics','Personalizada'];
const subs={
 'GT3':['World Series','Endurance','Fabricantes','Personalizada'],
 'GT4':['Cup','Touring','Fabricantes','Personalizada'],
 'VGT':['Vision Trophy','Concept Cars','Eléctricos','Personalizada'],
 'Formula GT7':['Super Formula','X2019 Cup','Personalizada'],
 'Road Cars':['Deportivos Modernos','Deportivos Clásicos','JDM 90s','American Sportcars','American Classics','Personalizada'],
 'Deportivos Modernos':['Supercars modernos','Porsche Cup','Ferrari Cup','Personalizada'],
 'Deportivos Clásicos':['Ferrari F40 Cup','Clásicos Europeos','Personalizada'],
 'American Sportcars':['Viper Cup','Ford GT Cup','Corvette Cup','Personalizada'],
 'American Classics':['Muscle Cars','America 70s','Personalizada'],
 'Personalizada':['Personalizada']
};
let state=load();
function seed(){return{version:VERSION,activeChampionshipId:null,garage:{owned:[],favorites:[]},championships:[],trash:[],settings:{firstRun:true}}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(t){const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function car(id){return GT7_CARS.find(c=>c.id===id)}
function circuit(id){return GT7_CIRCUITS.find(c=>c.id===id)}
function ownedCars(){return GT7_CARS.filter(c=>state.garage.owned.includes(c.id))}
function activeChamp(){return state.championships.find(c=>c.id===state.activeChampionshipId)||state.championships.find(c=>c.status!=='archived')||null}
function pointsFor(pos){return defaultPoints[pos-1]||0}
function computeStandings(ch){let map={};ch.grid.forEach(p=>map[p.id]={id:p.id,num:p.num,name:p.name,carId:p.carId,pts:0,wins:0,podiums:0,poles:0,fl:0,entries:0});ch.races.forEach(r=>{if(!r.result)return;r.result.positions.forEach((pid,i)=>{if(!map[pid])return;map[pid].pts+=pointsFor(i+1);map[pid].entries++; if(i===0)map[pid].wins++; if(i<3)map[pid].podiums++;}); if(r.result.pole&&map[r.result.pole]){map[r.result.pole].pts+=1;map[r.result.pole].poles++} if(r.result.fastest&&map[r.result.fastest]){map[r.result.fastest].pts+=1;map[r.result.fastest].fl++}});return Object.values(map).sort((a,b)=>b.pts-a.pts||b.wins-a.wins||b.podiums-a.podiums)}
function nextRace(ch){return ch?.races.find(r=>!r.result)||null}
function completedRaces(ch){return ch?.races.filter(r=>r.result).length||0}
function header(sub='Campeonatos offline de GT7 con Race Control, Garaje GT7 y plantillas para carreras personalizadas.'){return `<div class="top"><div class="kicker">${VERSION}</div><div class="title">GT7 Championship Manager</div><div class="subtitle">${sub}</div></div>`}
function nav(view){return `<div class="tabs">${[['home','Inicio'],['champ','Campeonatos'],['garage','Garaje'],['library','Biblioteca'],['settings','Ajustes']].map(([v,n])=>`<button class="tab ${view===v?'active':''}" data-nav="${v}">${n}</button>`).join('')}</div>`}
function render(view='home'){document.body.innerHTML=`<div id="app" class="app"></div>`;const app=$('#app');app.innerHTML=routes[view]()+nav(view);document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));bindCommon()}
const routes={home,champ,garage,library,settings};
function home(){const ch=activeChamp(); if(!ownedCars().length)return header('Bienvenido. El primer paso es crear tu Garaje GT7.')+`<div class="card hero"><div class="big">Configura tu Garaje GT7</div><p class="muted">Marca los coches que tienes en GT7. Serán los coches disponibles para crear plantillas de campeonato.</p><button class="btn primary" data-nav="garage">Ir al Garaje GT7</button></div>`; if(!ch)return header('Garaje listo. Ahora puedes crear tu primer campeonato.')+`<div class="card hero"><div class="big">Crea tu primer campeonato</div><p class="muted">El asistente generará calendario, plantilla GT7 y Race Control.</p><button class="btn primary" data-action="createChamp">Crear campeonato</button></div>`; const nr=nextRace(ch), stand=computeStandings(ch); return header('Centro de control orientado a la próxima carrera.')+`<div class="card hero champ-card"><div class="pill">Campeonato activo</div><div class="big">${ch.name}</div><p class="muted">${ch.category} · ${ch.subcategory} · Carrera ${completedRaces(ch)+1}/${ch.races.length}</p><button class="btn primary" data-action="openRace" data-id="${ch.id}">Continuar campeonato</button></div><div class="grid"><div class="stat"><span class="muted">Próxima carrera</span><b>${nr?circuit(nr.circuitId).name:'Temporada finalizada'}</b></div><div class="stat"><span class="muted">Líder</span><b>${stand[0]?.name||'—'}</b></div></div><div class="section-title">Clasificación rápida</div><div class="card">${stand.slice(0,5).map((s,i)=>`<div class="between item"><span>${i+1}. ${s.name}</span><b>${s.pts}</b></div>`).join('')||'<div class="empty">Sin resultados todavía.</div>'}</div>`}
function champ(){return header('Crea, continúa o administra tus campeonatos.')+`<div class="between"><div class="section-title">Campeonatos</div><button class="btn primary small" data-action="createChamp">Nuevo</button></div><div class="list">${state.championships.length?state.championships.map(ch=>`<div class="item champ-card"><div class="between"><div><b>${ch.name}</b><div class="muted">${ch.category} · ${ch.subcategory} · ${completedRaces(ch)}/${ch.races.length}</div></div><span class="pill">${ch.status}</span></div><div class="row" style="margin-top:12px"><button class="btn small primary" data-action="openRace" data-id="${ch.id}">Continuar</button><button class="btn small" data-action="setActive" data-id="${ch.id}">Activar</button><button class="btn small danger" data-action="deleteChamp" data-id="${ch.id}">Eliminar</button></div></div>`).join(''):'<div class="card empty">No hay campeonatos todavía.</div>'}</div>`}
function garage(){const makes=[...new Set(GT7_CARS.map(c=>c.make))].sort();return header('Biblioteca permanente de coches que tienes en GT7.')+`<div class="card"><div class="between"><div><b>Garaje GT7</b><div class="muted">${ownedCars().length} coches marcados como disponibles</div></div><button class="btn small" data-action="clearGarage">Limpiar</button></div><input id="carSearch" placeholder="Buscar coche, marca o categoría" style="margin-top:14px"></div><div id="carList">${carListHTML(GT7_CARS)}</div>`}
function carListHTML(list){const grouped={};list.forEach(c=>{(grouped[c.make]??=[]).push(c)});return Object.keys(grouped).sort().map(make=>`<div class="card"><div class="between"><b>${make}</b><span class="pill">${grouped[make].length}</span></div><div class="list" style="margin-top:12px">${grouped[make].map(c=>`<label class="item row"><input type="checkbox" data-car="${c.id}" ${state.garage.owned.includes(c.id)?'checked':''} style="width:22px"><span><b>${c.model}</b><div class="mini">${c.category} · ${c.sub} · ${c.country}</div></span></label>`).join('')}</div></div>`).join('')}
function library(){
 const asphalt=GT7_CIRCUITS.filter(c=>c.asphalt!==false);
 const grouped={}; asphalt.forEach(c=>{(grouped[c.location||c.name]??=[]).push(c)});
 return header('Datos reutilizables: categorías, circuitos y reglamentos base.')+`<div class="section-title">Categorías base</div><div class="card">${cats.map(c=>`<span class="pill" style="margin:4px">${c}</span>`).join('')}</div><div class="section-title">Circuitos de asfalto y variantes</div><div class="card muted">${Object.keys(grouped).length} localizaciones · ${asphalt.length} trazados/variantes. Tierra y nieve quedan fuera del selector principal.</div><div class="card list">${Object.keys(grouped).sort().map(loc=>`<div class="item"><b>${loc}</b><div class="muted">${grouped[loc][0].country}</div><div style="margin-top:8px">${grouped[loc].map(c=>`<span class="pill" style="margin:3px">${c.layout||c.name}${c.special?' · NS':''}</span>`).join('')}</div></div>`).join('')}</div><div class="section-title">Sistema de puntos RC1</div><div class="card"><p class="muted">Puntos tipo GT: ${defaultPoints.join(' - ')}. Pole +1. Vuelta rápida +1.</p></div>`}
function settings(){return header('Datos, versión y documentación.')+`<div class="card"><h2>Datos</h2><button class="btn" data-action="exportData">Exportar datos</button><button class="btn" data-action="importData" style="margin-top:10px">Importar datos</button><input type="file" id="importFile" class="hidden" accept="application/json"><button class="btn danger" data-action="wipe" style="margin-top:10px">Borrar todos los datos</button></div><div class="card"><h2>Versión</h2><p class="muted">GT7 Championship Manager · ${VERSION}</p><p class="muted"><b>Designed by JDM & ChatGPT</b></p></div>`}
function bindCommon(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.(b));const search=$('#carSearch'); if(search)search.oninput=()=>{$('#carList').innerHTML=carListHTML(GT7_CARS.filter(c=>(c.make+' '+c.model+' '+c.category+' '+c.sub).toLowerCase().includes(search.value.toLowerCase())));bindCommon()};document.querySelectorAll('[data-car]').forEach(cb=>cb.onchange=()=>{const id=cb.dataset.car;if(cb.checked&&!state.garage.owned.includes(id))state.garage.owned.push(id);if(!cb.checked)state.garage.owned=state.garage.owned.filter(x=>x!==id);save();toast('Garaje actualizado')})}
const actions={
createChamp(){showChampWizard()},
setActive(b){state.activeChampionshipId=b.dataset.id;save();toast('Campeonato activo');render('home')},
deleteChamp(b){if(confirm('¿Mover este campeonato a la papelera?')){state.championships=state.championships.filter(c=>c.id!==b.dataset.id); if(state.activeChampionshipId===b.dataset.id)state.activeChampionshipId=null;save();render('champ')}},
clearGarage(){if(confirm('¿Vaciar Garaje GT7?')){state.garage.owned=[];save();render('garage')}},
openRace(b){const ch=state.championships.find(c=>c.id===b.dataset.id);showRace(ch)},
exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gt7cm-backup.json';a.click()},
importData(){const f=$('#importFile');f.click();f.onchange=()=>{const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render('home')}catch(e){alert('Archivo no válido')}};r.readAsText(f.files[0])}},
wipe(){if(confirm('Borrar todos los datos locales?')){state=seed();save();render('home')}}};
function showChampWizard(){const owned=ownedCars(); if(owned.length<2){alert('Añade primero coches a tu Garaje GT7.');render('garage');return}document.querySelector('#app').innerHTML=header('Asistente de creación de campeonato.')+`<div class="card"><div class="form"><div class="label">Nombre</div><input id="wName" value="Gr.3 World Series"><div class="label">Temporada</div><input id="wSeason" value="2026"><div class="label">Categoría</div><select id="wCat">${cats.map(c=>`<option>${c}</option>`).join('')}</select><div class="label">Subcategoría</div><select id="wSub"></select><div class="label">Nombre del ajuste guardado en GT7</div><input id="wPreset" value="GT7CM Championship"><div class="label">Número de carreras</div><input id="wRounds" type="number" value="10" min="1" max="20"><button class="btn primary" id="nextW">Crear calendario y parrilla</button><button class="btn" data-nav="champ">Cancelar</button></div></div>`+nav('champ');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));const cat=$('#wCat'),sub=$('#wSub');function fill(){sub.innerHTML=(subs[cat.value]||['Personalizada']).map(s=>`<option>${s}</option>`).join('')}cat.onchange=fill;fill();$('#nextW').onclick=()=>createChampFromWizard()}
function createChampFromWizard(){const rounds=Number($('#wRounds').value)||10;const owned=ownedCars();const selected=owned.slice(0,20);const grid=Array.from({length:20},(_,i)=>{const c=selected[i%selected.length];return{id:uid(),num:i+1,name:i===0?'JDM':`IA ${String(i).padStart(2,'0')}`,type:i===0?'user':'ai',carId:c.id}});const races=Array.from({length:rounds},(_,i)=>{const ci=GT7_CIRCUITS[i%GT7_CIRCUITS.length];return{id:uid(),round:i+1,circuitId:ci.id,laps:ci.id.includes('nordschleife')?3:10,weather:'Variable',timeOfDay:'Tarde',bop:true,fuel:3,tyres:5,result:null}});const ch={id:uid(),name:$('#wName').value||'Nuevo campeonato',season:$('#wSeason').value||'2026',category:$('#wCat').value,subcategory:$('#wSub').value,status:'preparación',gt7Preset:$('#wPreset').value||'GT7CM Championship',points:defaultPoints,grid,races,createdAt:new Date().toISOString()};state.championships.push(ch);state.activeChampionshipId=ch.id;save();toast('Campeonato creado');showRace(ch)}
function showRace(ch){const r=nextRace(ch);const standings=computeStandings(ch);document.querySelector('#app').innerHTML=header('Race Control')+(r?`<div class="card hero"><div class="pill">${ch.name}</div><div class="big">${circuit(r.circuitId).name}</div><p class="muted">Carrera ${r.round}/${ch.races.length} · ${ch.category} · ${ch.subcategory}</p></div><div class="card"><h2>Checklist GT7</h2>${[['Ajuste GT7',ch.gt7Preset],['Circuito',circuit(r.circuitId).name],['Vueltas',r.laps],['Clima',r.weather],['Momento GT7',r.timeOfDay],['BoP',r.bop?'Activado':'Desactivado'],['Consumo',`x${r.fuel}`],['Desgaste',`x${r.tyres}`]].map(([a,b])=>`<label class="check"><input type="checkbox"><span><b>${a}</b><div class="muted">${b}</div></span></label>`).join('')}<button class="btn primary" data-action="resultForm" data-ch="${ch.id}" data-r="${r.id}">Registrar resultado</button></div>`:`<div class="card hero"><div class="big">Temporada finalizada</div><p class="muted">Todas las carreras tienen resultado.</p></div>`)+`<div class="section-title">Clasificación</div><div class="card">${standingsTable(standings)}</div>`+nav('home');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));document.querySelectorAll('[data-action="resultForm"]').forEach(b=>b.onclick=()=>showResultForm(ch,r))}
function standingsTable(st){return st.length?`<table class="table"><tr><th>#</th><th>Piloto</th><th>Pts</th></tr>${st.map((s,i)=>`<tr><td>${i+1}</td><td>${s.name}<div class="mini">${car(s.carId)?.make} ${car(s.carId)?.model}</div></td><td><b>${s.pts}</b></td></tr>`).join('')}</table>`:'<div class="empty">Sin resultados todavía.</div>'}
function showResultForm(ch,r){const options=ch.grid.map(p=>`<option value="${p.id}">${p.num} · ${p.name} · ${car(p.carId)?.make} ${car(p.carId)?.model}</option>`).join('');document.querySelector('#app').innerHTML=header('Registrar resultado')+`<div class="card"><p class="muted">Introduce el orden de llegada. Para la Build 001 puedes completar al menos tus primeras posiciones y dejar el resto en orden de parrilla.</p><div class="form" id="posList">${ch.grid.map((p,i)=>`<div><div class="label">P${i+1}</div><select class="posSel">${options}</select></div>`).join('')}</div><div class="label" style="margin-top:14px">Pole</div><select id="pole"><option value="">Sin punto</option>${options}</select><div class="label">Vuelta rápida</div><select id="fastest"><option value="">Sin punto</option>${options}</select><button class="btn primary" id="saveResult" style="margin-top:14px">Actualizar campeonato</button></div>`+nav('home');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));document.querySelectorAll('.posSel').forEach((s,i)=>s.value=ch.grid[i].id);$('#saveResult').onclick=()=>{const positions=[...document.querySelectorAll('.posSel')].map(s=>s.value); if(new Set(positions).size!==positions.length){alert('Hay pilotos repetidos en el resultado.');return}r.result={positions,pole:$('#pole').value||null,fastest:$('#fastest').value||null,savedAt:new Date().toISOString()};ch.status='en curso';save();toast('Resultado guardado');showRace(ch)}}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js?v=rc1b002').catch(()=>{})}
render('home');
})();
