window.GT7_CARS=[
{id:'porsche-911-rsr-17',make:'Porsche',model:"911 RSR (991) '17",year:2017,category:'GT3',sub:'GT3',country:'Alemania',type:'Race Car'},
{id:'bmw-m6-gt3-sprint-16',make:'BMW',model:"M6 GT3 Sprint Model '16",year:2016,category:'GT3',sub:'GT3',country:'Alemania',type:'Race Car'},
{id:'bmw-m6-gt3-endurance-16',make:'BMW',model:"M6 GT3 Endurance Model '16",year:2016,category:'GT3',sub:'GT3',country:'Alemania',type:'Race Car'},
{id:'ferrari-458-gt3-13',make:'Ferrari',model:"458 Italia GT3 '13",year:2013,category:'GT3',sub:'GT3',country:'Italia',type:'Race Car'},
{id:'lambo-huracan-gt3-15',make:'Lamborghini',model:"Huracán GT3 '15",year:2015,category:'GT3',sub:'GT3',country:'Italia',type:'Race Car'},
{id:'audi-r8-lms-evo-19',make:'Audi',model:"R8 LMS Evo '19",year:2019,category:'GT3',sub:'GT3',country:'Alemania',type:'Race Car'},
{id:'mercedes-amg-gt3-20',make:'Mercedes-AMG',model:"AMG GT3 '20",year:2020,category:'GT3',sub:'GT3',country:'Alemania',type:'Race Car'},
{id:'nissan-gt-r-gt3-18',make:'Nissan',model:"GT-R NISMO GT3 '18",year:2018,category:'GT3',sub:'GT3',country:'Japón',type:'Race Car'},
{id:'toyota-supra-gt500-97',make:'Toyota',model:"Supra GT500 '97",year:1997,category:'GT3',sub:'GT500',country:'Japón',type:'Race Car'},
{id:'honda-nsx-gt500-00',make:'Honda',model:"NSX GT500 '00",year:2000,category:'GT3',sub:'GT500',country:'Japón',type:'Race Car'},
{id:'mazda-rx-vision-gt3',make:'Mazda',model:"RX-VISION GT3 Concept",year:2020,category:'GT3',sub:'VGT GT3',country:'Japón',type:'Race Car'},
{id:'toyota-gr-supra-race-car-19',make:'Toyota',model:"GR Supra Race Car '19",year:2019,category:'GT4',sub:'GT4',country:'Japón',type:'Race Car'},
{id:'porsche-cayman-gt4-16',make:'Porsche',model:"Cayman GT4 Clubsport '16",year:2016,category:'GT4',sub:'GT4',country:'Alemania',type:'Race Car'},
{id:'nissan-silvia-touring-car',make:'Nissan',model:'Silvia Touring Car',year:null,category:'GT4',sub:'Touring Car',country:'Japón',type:'Race Car'},
{id:'ferrari-f40-92',make:'Ferrari',model:"F40 '92",year:1992,category:'Road Cars',sub:'Deportivos Clásicos',country:'Italia',type:'Road Car'},
{id:'ferrari-f50-95',make:'Ferrari',model:"F50 '95",year:1995,category:'Road Cars',sub:'Deportivos Clásicos',country:'Italia',type:'Road Car'},
{id:'porsche-carrera-gt-04',make:'Porsche',model:"Carrera GT '04",year:2004,category:'Road Cars',sub:'Deportivos Modernos',country:'Alemania',type:'Road Car'},
{id:'ford-mustang-boss-429-69',make:'Ford',model:"Mustang Boss 429 '69",year:1969,category:'Road Cars',sub:'American Classics',country:'Estados Unidos',type:'Road Car'},
{id:'chevrolet-camaro-z28-69',make:'Chevrolet',model:"Camaro Z28 '69",year:1969,category:'Road Cars',sub:'American Classics',country:'Estados Unidos',type:'Road Car'},
{id:'dodge-charger-rt-70',make:'Dodge',model:"Charger R/T 426 Hemi '68",year:1968,category:'Road Cars',sub:'American Classics',country:'Estados Unidos',type:'Road Car'},
{id:'plymouth-superbird-70',make:'Plymouth',model:"Superbird '70",year:1970,category:'Road Cars',sub:'American Classics',country:'Estados Unidos',type:'Road Car'},
{id:'chevrolet-corvette-c3-69',make:'Chevrolet',model:"Corvette Stingray Convertible (C3) '69",year:1969,category:'Road Cars',sub:'American Classics',country:'Estados Unidos',type:'Road Car'},
{id:'ford-gt-06',make:'Ford',model:"GT '06",year:2006,category:'Road Cars',sub:'American Sportcars',country:'Estados Unidos',type:'Road Car'},
{id:'dodge-viper-gts-02',make:'Dodge',model:"Viper GTS '02",year:2002,category:'Road Cars',sub:'American Sportcars',country:'Estados Unidos',type:'Road Car'},
{id:'tesla-model-s-signature-12',make:'Tesla',model:"Model S Signature Performance '12",year:2012,category:'Road Cars',sub:'Deportivos Modernos',country:'Estados Unidos',type:'Road Car'},
{id:'toyota-supra-rz-97',make:'Toyota',model:"Supra RZ '97",year:1997,category:'Road Cars',sub:'JDM 90s',country:'Japón',type:'Road Car'},
{id:'nissan-skyline-gt-r-vspec-ii-94',make:'Nissan',model:"Skyline GT-R V·spec II (R32) '94",year:1994,category:'Road Cars',sub:'JDM 90s',country:'Japón',type:'Road Car'},
{id:'honda-nsx-type-r-02',make:'Honda',model:"NSX Type R '02",year:2002,category:'Road Cars',sub:'JDM',country:'Japón',type:'Road Car'},
{id:'mazda-rx7-spirit-r-02',make:'Mazda',model:"RX-7 Spirit R Type A (FD) '02",year:2002,category:'Road Cars',sub:'JDM',country:'Japón',type:'Road Car'},
{id:'mclaren-vgt',make:'McLaren',model:'Ultimate Vision Gran Turismo',year:null,category:'VGT',sub:'Vision GT',country:'Reino Unido',type:'Concept'},
{id:'bugatti-vgt',make:'Bugatti',model:'Vision Gran Turismo',year:null,category:'VGT',sub:'Vision GT',country:'Francia',type:'Concept'},
{id:'redbull-x2019',make:'Gran Turismo',model:'Red Bull X2019 Competition',year:2019,category:'Formula GT7',sub:'Formula',country:'Japón',type:'Race Car'},
{id:'super-formula-toyota-23',make:'Super Formula',model:"SF23 Super Formula / Toyota '23",year:2023,category:'Formula GT7',sub:'Super Formula',country:'Japón',type:'Race Car'},
{id:'super-formula-honda-23',make:'Super Formula',model:"SF23 Super Formula / Honda '23",year:2023,category:'Formula GT7',sub:'Super Formula',country:'Japón',type:'Race Car'}
];
