window.GT7_CARS = [
{id:'abarth-595-70',make:'Abarth',model:'595 SS',year:'1970',category:'Road Cars',sub:'Deportivos Clásicos',country:'Italia',type:'Producción'},
{id:'alfa-155-ti-93',make:'Alfa Romeo',model:'155 2.5 V6 TI',year:'1993',category:'Race Cars',sub:'Touring Classics',country:'Italia',type:'Carreras'},
{id:'alfa-4c-gr3',make:'Alfa Romeo',model:'4C Gr.3',year:'2014',category:'GT3',sub:'Gr.3',country:'Italia',type:'Carreras'},
{id:'alfa-4c-gr4',make:'Alfa Romeo',model:'4C Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'Italia',type:'Carreras'},
{id:'amg-gt3-16',make:'Mercedes-AMG',model:'AMG GT3',year:'2016',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'amg-gt3-20',make:'Mercedes-AMG',model:'AMG GT3',year:'2020',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'amg-gr4',make:'Mercedes-AMG',model:'SLS AMG Gr.4',year:'2011',category:'GT4',sub:'Gr.4',country:'Alemania',type:'Carreras'},
{id:'aston-db11-16',make:'Aston Martin',model:'DB11',year:'2016',category:'Road Cars',sub:'Deportivos Modernos',country:'Reino Unido',type:'Producción'},
{id:'aston-dbr9-10',make:'Aston Martin',model:'DBR9 GT1',year:'2010',category:'Race Cars',sub:'GT1',country:'Reino Unido',type:'Carreras'},
{id:'aston-v12-vantage-12',make:'Aston Martin',model:'V12 Vantage GT3',year:'2012',category:'GT3',sub:'Gr.3',country:'Reino Unido',type:'Carreras'},
{id:'aston-vantage-gr4',make:'Aston Martin',model:'Vantage Gr.4',year:'2018',category:'GT4',sub:'Gr.4',country:'Reino Unido',type:'Carreras'},
{id:'audi-r8-lms-15',make:'Audi',model:'R8 LMS',year:'2015',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'audi-r8-lms-evo-19',make:'Audi',model:'R8 LMS Evo',year:'2019',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'audi-tt-cup-16',make:'Audi',model:'TT Cup',year:'2016',category:'GT4',sub:'Gr.4',country:'Alemania',type:'Carreras'},
{id:'bmw-m3-89',make:'BMW',model:'M3 Sport Evolution',year:'1989',category:'Road Cars',sub:'Deportivos Clásicos',country:'Alemania',type:'Producción'},
{id:'bmw-m4-14',make:'BMW',model:'M4 Coupé',year:'2014',category:'Road Cars',sub:'Deportivos Modernos',country:'Alemania',type:'Producción'},
{id:'bmw-m6-gt3-16',make:'BMW',model:'M6 GT3 Endurance Model',year:'2016',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'bmw-m6-sprint-16',make:'BMW',model:'M6 GT3 Sprint Model',year:'2016',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'bmw-m4-gr4',make:'BMW',model:'M4 Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'Alemania',type:'Carreras'},
{id:'chevrolet-camaro-z28-69',make:'Chevrolet',model:'Camaro Z28',year:'1969',category:'Road Cars',sub:'American Classics',country:'EE.UU.',type:'Producción'},
{id:'chevrolet-corvette-c3-69',make:'Chevrolet',model:'Corvette Stingray Convertible C3',year:'1969',category:'Road Cars',sub:'American Classics',country:'EE.UU.',type:'Producción'},
{id:'chevrolet-corvette-c7-gr3',make:'Chevrolet',model:'Corvette C7 Gr.3',year:'2014',category:'GT3',sub:'Gr.3',country:'EE.UU.',type:'Carreras'},
{id:'chevrolet-corvette-c7-gr4',make:'Chevrolet',model:'Corvette C7 Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'EE.UU.',type:'Carreras'},
{id:'dodge-challenger-70',make:'Dodge',model:'Challenger R/T',year:'1970',category:'Road Cars',sub:'American Classics',country:'EE.UU.',type:'Producción'},
{id:'dodge-viper-gr3',make:'Dodge',model:'Viper SRT GT3-R',year:'2015',category:'GT3',sub:'Gr.3',country:'EE.UU.',type:'Carreras'},
{id:'dodge-viper-gr4',make:'Dodge',model:'Viper Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'EE.UU.',type:'Carreras'},
{id:'ferrari-458-gt3-13',make:'Ferrari',model:'458 Italia GT3',year:'2013',category:'GT3',sub:'Gr.3',country:'Italia',type:'Carreras'},
{id:'ferrari-458-gr4',make:'Ferrari',model:'458 Italia Gr.4',year:'2013',category:'GT4',sub:'Gr.4',country:'Italia',type:'Carreras'},
{id:'ferrari-f40-92',make:'Ferrari',model:'F40',year:'1992',category:'Road Cars',sub:'Deportivos Clásicos',country:'Italia',type:'Producción'},
{id:'ferrari-f50-95',make:'Ferrari',model:'F50',year:'1995',category:'Road Cars',sub:'Deportivos Clásicos',country:'Italia',type:'Producción'},
{id:'ford-mustang-boss-69',make:'Ford',model:'Mustang Boss 429',year:'1969',category:'Road Cars',sub:'American Classics',country:'EE.UU.',type:'Producción'},
{id:'ford-mustang-mach-71',make:'Ford',model:'Mustang Mach 1',year:'1971',category:'Road Cars',sub:'American Classics',country:'EE.UU.',type:'Producción'},
{id:'ford-gt-lm-spec2',make:'Ford',model:'GT LM Race Car Spec II',year:'2018',category:'GT3',sub:'Gr.3',country:'EE.UU.',type:'Carreras'},
{id:'ford-mustang-gr3',make:'Ford',model:'Mustang Gr.3',year:'2015',category:'GT3',sub:'Gr.3',country:'EE.UU.',type:'Carreras'},
{id:'ford-mustang-gr4',make:'Ford',model:'Mustang Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'EE.UU.',type:'Carreras'},
{id:'honda-nsx-gr3',make:'Honda',model:'NSX Gr.3',year:'2017',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'honda-nsx-gr4',make:'Honda',model:'NSX Gr.4',year:'2017',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'honda-civic-ek-98',make:'Honda',model:'Civic Type R EK',year:'1998',category:'Road Cars',sub:'JDM 90s',country:'Japón',type:'Producción'},
{id:'jaguar-f-type-gr3',make:'Jaguar',model:'F-type Gr.3',year:'2014',category:'GT3',sub:'Gr.3',country:'Reino Unido',type:'Carreras'},
{id:'jaguar-f-type-gr4',make:'Jaguar',model:'F-type Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'Reino Unido',type:'Carreras'},
{id:'lamborghini-huracan-gt3-15',make:'Lamborghini',model:'Huracán GT3',year:'2015',category:'GT3',sub:'Gr.3',country:'Italia',type:'Carreras'},
{id:'lamborghini-huracan-gr4',make:'Lamborghini',model:'Huracán Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'Italia',type:'Carreras'},
{id:'lexus-rcf-gt3-17',make:'Lexus',model:'RC F GT3',year:'2017',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'lexus-rcf-gr4',make:'Lexus',model:'RC F Gr.4',year:'2016',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'mazda-rx-vision-gt3',make:'Mazda',model:'RX-Vision GT3 Concept',year:'2020',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'mazda-atenza-gr4',make:'Mazda',model:'Atenza Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'mclaren-650s-gt3-15',make:'McLaren',model:'650S GT3',year:'2015',category:'GT3',sub:'Gr.3',country:'Reino Unido',type:'Carreras'},
{id:'mclaren-650s-gr4',make:'McLaren',model:'650S Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'Reino Unido',type:'Carreras'},
{id:'mitsubishi-lancer-evo-final-15',make:'Mitsubishi',model:'Lancer Evolution Final Edition',year:'2015',category:'Road Cars',sub:'JDM Modernos',country:'Japón',type:'Producción'},
{id:'nissan-gt-r-gt3-18',make:'Nissan',model:'GT-R NISMO GT3',year:'2018',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'nissan-gt-r-gr4',make:'Nissan',model:'GT-R Gr.4',year:'2017',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'nissan-skyline-r32-94',make:'Nissan',model:'Skyline GT-R V-spec II R32',year:'1994',category:'Road Cars',sub:'JDM 90s',country:'Japón',type:'Producción'},
{id:'peugeot-rcz-gr3',make:'Peugeot',model:'RCZ Gr.3',year:'2015',category:'GT3',sub:'Gr.3',country:'Francia',type:'Carreras'},
{id:'peugeot-rcz-gr4',make:'Peugeot',model:'RCZ Gr.4',year:'2015',category:'GT4',sub:'Gr.4',country:'Francia',type:'Carreras'},
{id:'porsche-911-rsr-17',make:'Porsche',model:'911 RSR (991)',year:'2017',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'porsche-cayman-gt4',make:'Porsche',model:'Cayman GT4 Clubsport',year:'2016',category:'GT4',sub:'Gr.4',country:'Alemania',type:'Carreras'},
{id:'porsche-911-gt3rs-22',make:'Porsche',model:'911 GT3 RS (992)',year:'2022',category:'Road Cars',sub:'Deportivos Modernos',country:'Alemania',type:'Producción'},
{id:'porsche-carrera-gt-04',make:'Porsche',model:'Carrera GT',year:'2004',category:'Road Cars',sub:'Deportivos Modernos',country:'Alemania',type:'Producción'},
{id:'renault-rs01-gt3',make:'Renault Sport',model:'R.S.01 GT3',year:'2016',category:'GT3',sub:'Gr.3',country:'Francia',type:'Carreras'},
{id:'subaru-wrx-gr3',make:'Subaru',model:'WRX Gr.3',year:'2015',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'subaru-wrx-gr4',make:'Subaru',model:'WRX Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'toyota-supra-gt500-97',make:'Toyota',model:'Castrol TOM\'S Supra',year:'1997',category:'Race Cars',sub:'GT500 Classics',country:'Japón',type:'Carreras'},
{id:'toyota-gr-supra-gt3',make:'Toyota',model:'GR Supra Racing Concept',year:'2018',category:'GT3',sub:'Gr.3',country:'Japón',type:'Carreras'},
{id:'toyota-86-gr4',make:'Toyota',model:'86 Gr.4',year:'2016',category:'GT4',sub:'Gr.4',country:'Japón',type:'Carreras'},
{id:'vw-beetle-gr3',make:'Volkswagen',model:'Beetle Gr.3',year:'2016',category:'GT3',sub:'Gr.3',country:'Alemania',type:'Carreras'},
{id:'vw-scirocco-gr4',make:'Volkswagen',model:'Scirocco Gr.4',year:'2014',category:'GT4',sub:'Gr.4',country:'Alemania',type:'Carreras'},
{id:'redbull-x2019',make:'Gran Turismo',model:'Red Bull X2019 Competition',year:'2019',category:'Formula GT7',sub:'Formula GT7',country:'Japón',type:'Carreras'},
{id:'super-formula-toyota-23',make:'Super Formula',model:'SF23 Toyota',year:'2023',category:'Formula GT7',sub:'Super Formula',country:'Japón',type:'Carreras'},
{id:'super-formula-honda-23',make:'Super Formula',model:'SF23 Honda',year:'2023',category:'Formula GT7',sub:'Super Formula',country:'Japón',type:'Carreras'},
{id:'bugatti-vgt-gr1',make:'Bugatti',model:'Vision Gran Turismo Gr.1',year:'2015',category:'VGT',sub:'VGT',country:'Francia',type:'Concept'},
{id:'mazda-lm55-vgt',make:'Mazda',model:'LM55 Vision Gran Turismo',year:'2015',category:'VGT',sub:'VGT',country:'Japón',type:'Concept'},
{id:'mclaren-vgt',make:'McLaren',model:'Ultimate Vision Gran Turismo',year:'2017',category:'VGT',sub:'VGT',country:'Reino Unido',type:'Concept'}
];
