window.GT7_CIRCUITS = [
{name:'Trial Mountain Circuit',country:'Original',sophy:false},
{name:'Deep Forest Raceway',country:'Original',sophy:false},
{name:'Grand Valley Highway 1',country:'Original',sophy:false},
{name:'High Speed Ring',country:'Original',sophy:false},
{name:'Autodrome Lago Maggiore',country:'Original',sophy:false},
{name:'Dragon Trail - Seaside',country:'Croacia',sophy:false},
{name:'Circuit de Spa-Francorchamps',country:'Bélgica',sophy:false},
{name:'Nürburgring GP',country:'Alemania',sophy:false},
{name:'Nürburgring Nordschleife',country:'Alemania',sophy:false,special:'Sprint 1 vuelta + carrera 3 vueltas'},
{name:'Suzuka Circuit',country:'Japón',sophy:false},
{name:'Fuji International Speedway',country:'Japón',sophy:false},
{name:'Tokyo Expressway',country:'Japón',sophy:false},
{name:'Autódromo de Interlagos',country:'Brasil',sophy:false},
{name:'Watkins Glen International',country:'EE.UU.',sophy:false},
{name:'WeatherTech Raceway Laguna Seca',country:'EE.UU.',sophy:false},
{name:'Daytona Road Course',country:'EE.UU.',sophy:false},
{name:'Michelin Raceway Road Atlanta',country:'EE.UU.',sophy:false},
{name:'Circuit de Barcelona-Catalunya',country:'España',sophy:false},
{name:'Circuit de la Sarthe',country:'Francia',sophy:false},
{name:'Red Bull Ring',country:'Austria',sophy:false},
{name:'Mount Panorama',country:'Australia',sophy:false},
{name:'Brands Hatch GP',country:'Reino Unido',sophy:false},
{name:'Goodwood Motor Circuit',country:'Reino Unido',sophy:false},
{name:'Monza',country:'Italia',sophy:false},
{name:'Sardegna Road Track',country:'Italia',sophy:false},
{name:'Alsace',country:'Francia',sophy:false},
{name:'Kyoto Driving Park',country:'Japón',sophy:false},
{name:'Blue Moon Bay Speedway',country:'EE.UU.',sophy:false},
{name:'Northern Isle Speedway',country:'EE.UU.',sophy:false}
];
